const fs = require('fs');
const path = 'C:/Users/YeZhimin/.openclaw/workspace-dev/proposals/amblyopia-training/web/src/pages/GameRunner.tsx';
const append = `
h); } }); ctx.fillStyle = '#FFF'; ctx.font = '14px Arial'; ctx.textAlign = 'center'; ctx.fillText('Depth: click matching pairs!', width / 2, 40); }
  function renderVisualSearchMaze(ctx: CanvasRenderingContext2D, data: any, width: number, height: number) {
    const cs=data.cellSize;
    for(let y=0;y<data.gridSize;y++){for(let x=0;x<data.gridSize;x++){
      const px=data.offsetX+x*cs,py=data.offsetY+y*cs;
      const isWall=data.walls.some((w:any)=>w.x===x&&w.y===y);
      const isExit=x===data.exit.x&&y===data.exit.y;
      const isPlayer=x===data.player.x&&y===data.player.y;
      ctx.fillStyle=isWall?'#2D3748':isExit?'#48BB78':'rgba(255,255,255,0.03)';
      ctx.fillRect(px,py,cs,cs);
      ctx.strokeStyle='rgba(255,255,255,0.1)';ctx.lineWidth=1;ctx.strokeRect(px,py,cs,cs);
      if(isPlayer){ctx.fillStyle='#FFD700';ctx.beginPath();ctx.arc(px+cs/2,py+cs/2,cs/3,0,Math.PI*2);ctx.fill();}
    }}
    ctx.fillStyle='#FFF';ctx.font='14px Arial';ctx.textAlign='center';ctx.fillText('Find path to exit!',width/2,40);
  }
  function renderQuickMatch(ctx: CanvasRenderingContext2D, data: any, width: number, height: number) {
    data.cards.forEach((card:any)=>{
      ctx.fillStyle=card.isMatched?'rgba(72,187,120,0.5)':'#2D3748';
      ctx.fillRect(card.x,card.y,card.width,card.height);
      if(data.currentShowing===card.id||card.isMatched){
        ctx.fillStyle=card.isMatched?'#48BB78':'#4A90E2';ctx.fillRect(card.x+4,card.y+4,card.width-8,card.height-8);
        ctx.font=card.width*0.55+'px Arial';ctx.fillStyle='#FFF';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(card.emoji,card.x+card.width/2,card.y+card.height/2);
      }else{ctx.fillStyle='rgba(255,255,255,0.2)';ctx.font='28px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('?',card.x+card.width/2,card.y+card.height/2);}
      ctx.strokeStyle=card.isMatched?'#48BB78':'#4A5568';ctx.lineWidth=2;ctx.strokeRect(card.x,card.y,card.width,card.height);
    });
    ctx.fillStyle='#FFF';ctx.font='14px Arial';ctx.textAlign='center';ctx.fillText('Quick Match! Pairs: '+data.matched, width/2, 40);
  }
  function colorName(c:string){return{'#FF4444':'红','#44AAFF':'蓝','#44FF44':'绿','#FFAA00':'橙'}[c]||c;}
  function addParticles(x:number,y:number,color:string,count:number){const d=gameDataRef.current;for(let i=0;i<count;i++){const a=Math.PI*2/count*i,s=50+Math.random()*100;d.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-100,color,radius:2+Math.random()*4,life:1});}}
  function addScorePopup(x:number,y:number,score:number,color:string){gameDataRef.current.scorePopups.push({x,y:y-20,score,color,life:1});}
  function handleCanvasClick(e: React.MouseEvent<HTMLCanvasElement>){
    const canvas=canvasRef.current;if(!canvas||gameState.isPaused||!gameState.isRunning)return;
    const rect=canvas.getBoundingClientRect();const x=e.clientX-rect.left,y=e.clientY-rect.top;const d=gameDataRef.current;let hit=false;
    switch(gameId){
      case 'stripe-chase':{const t=d.target;const dist=Math.sqrt((x-t.x)**2+(y-t.y)**2);if(dist<t.radius){hit=true;addParticles(x,y,'#FFD700',10);addScorePopup(x,y,10,'#FFD700');t.x=50+Math.random()*(d.width-100);t.y=50+Math.random()*(d.height-100);}break;}
      case 'dot-pop':{d.dots.forEach((dot:any)=>{if(!dot.isPopped){const dd=Math.sqrt((x-dot.x)**2+(y-dot.y)**2);if(dd<dot.radius){if(dot.color===d.targetColor){hit=true;addParticles(dot.x,dot.y,dot.color,8);}dot.isPopped=true;}}});if(!d.dots.some((dd:any)=>!dd.isPopped&&dd.color===d.targetColor))setGameState(p=>({...p,isComplete:true}));break;}
      case 'memory-flip':{if(!d.canClick||d.showing)break;d.cards.forEach((card:any)=>{if(x>=card.x&&x<=card.x+card.width&&y>=card.y&&y<=card.y+card.height&&!card.isFlipped&&!card.isMatched&&d.flippedCards.length<2){card.isFlipped=true;d.flippedCards.push(card);if(d.flippedCards.length===2){if(d.flippedCards[0].emoji===d.flippedCards[1].emoji){d.flippedCards.forEach(c=>{c.isMatched=true;c.isFlipped=false;});d.matchedPairs++;hit=true;addParticles(card.x+card.width/2,card.y+card.height/2,'#48BB78',12);addScorePopup(card.x+card.width/2,card.y+card.height/2,20,'#48BB78');if(d.matchedPairs===d.cards.length/2)setGameState(p=>({...p,isComplete:true}));}else{setTimeout(()=>d.flippedCards.forEach((c:any)=>c.isFlipped=false),800);}d.flippedCards=[];}}});break;}
      case 'fusion-puzzle':{d.pieces.forEach((piece:any)=>{const dx=x-piece.x,dy=y-piece.y;if(Math.sqrt(dx*dx+dy*dy)<piece.size/2){const inPlace=Math.abs(piece.x-piece.correctX)<piece.size/2&&Math.abs(piece.y-piece.correctY)<piece.size/2;if(inPlace){hit=true;addParticles(piece.x,piece.y,'#48BB78',8);addScorePopup(piece.x,piece.y,15,'#48BB78');d.placed++;if(d.placed===d.pieces.length)setGameState(p=>({...p,isComplete:true}));}}});break;}
      case 'draw-line':{const path=d.paths[d.currentPathIdx];if(!path)break;const dot=path.dots[d.currentDotIdx];const dist=Math.sqrt((x-dot.x)**2+(y-dot.y)**2);if(dist<25){dot.hit=true;hit=true;addParticles(dot.x,dot.y,'#48BB78',8);addScorePopup(dot.x,dot.y,10,'#48BB78');d.dotsHit++;if(d.currentDotIdx<path.dots.length-1){d.currentDotIdx++;}else{path.completed=true;if(d.currentPathIdx<d.paths.length-1){d.currentPathIdx++;d.currentDotIdx=0;}else{setGameState(p=>({...p,isComplete:true}));}}}break;}
      case 'accommodation-lift':{const t=d.targets[d.currentIndex];if(!t||t.hit)break;const dist=Math.sqrt((x-t.x)**2+(y-t.y)**2);if(dist<d.targetRadius+10){hit=true;t.hit=true;addParticles(t.x,t.y,t.isNear?'#FF6B6B':'#6B9FFF',10);addScorePopup(t.x,t.y,10,'#48BB78');if(d.currentIndex<d.targets.length-1){d.currentIndex++;d.isNear=d.targets[d.currentIndex].isNear;}else{setGameState(p=>({...p,isComplete:true}));}}break;}
      case 'sf-matching':{if(!d.canClick||d.showing)break;d.cards.forEach((card:any)=>{if(x>=card.x&&x<=card.x+card.width&&y>=card.y&&y<=card.y+card.height&&!card.isFlipped&&!card.isMatched&&d.flipped.length<2){card.isFlipped=true;d.flipped.push(card);if(d.flipped.length===2){if(d.flipped[0].pattern===d.flipped[1].pattern){d.flipped.forEach(c=>c.isMatched=true);d.matched++;hit=true;addParticles(card.x+card.width/2,card.y+card.height/2,'#48BB78',10);addScorePopup(card.x+card.width/2,card.y+card.height/2,20,'#48BB78');if(d.matched===d.cards.length/2)setGameState(p=>({...p,isComplete:true}));}else{setTimeout(()=>d.flipped.forEach((c:any)=>c.isFlipped=false),1000);}d.flipped=[];}}});break;}
      case 'depth-blocks':{let clicked:any=null;d.redBlocks.forEach((b:any)=>{if(b.matched)return;const dx=x-b.x-b.depth*0.5,dy=y-b.y-b.depth*0.5;if(Math.abs(dx)<b.size/2&&Math.abs(dy)<b.size/2)clicked={type:'red',block:b};});d.blueBlocks.forEach((b:any)=>{if(b.matched)return;const dx=x-b.x-b.depth*0.5,dy=y-b.y-b.depth*0.5;if(Math.abs(dx)<b.size/2&&Math.abs(dy)<b.size/2)clicked={type:'blue',block:b};});if(clicked){if(clicked.type==='red'){d.selectedRed=d.selectedRed===clicked.block.id?null:clicked.block.id;}else{d.selectedBlue=d.selectedBlue===clicked.block.id?null:clicked.block.id;}if(d.selectedRed!==null&&d.selectedBlue!==null){const rb=d.redBlocks.find((b:any)=>b.id===d.selectedRed);const bb=d.blueBlocks.find((b:any)=>b.id===d.selectedBlue);if(rb&&bb&&rb.depth===bb.depth){rb.matched=true;bb.matched=true;d.selectedRed=null;d.selectedBlue=null;d.matched++;hit=true;addParticles(rb.x,rb.y,'#48BB78',12);addScorePopup(rb.x,rb.y,25,'#48BB78');if(d.matched===4)setGameState(p=>({...p,isComplete:true}));}else{setTimeout(()=>{d.selectedRed=null;d.selectedBlue=null;},500);}}}break;}
      case 'visual-search-maze':{const cs=data.cellSize;const mx=Math.floor((x-data.offsetX)/cs);const my=Math.floor((y-data.offsetY)/cs);if(mx>=0&&mx<data.gridSize&&my>=0&&my<data.gridSize){const isWall=data.walls.some((w:any)=>w.x===mx&&w.y===my);if(!isWall){const px=data.player.x,py=data.player.y;const dist=Math.abs(mx-px)+Math.abs(my-py);if(dist===1){data.player={x:mx,y:my};data.visited[my][mx]=true;data.searchCount++;if(mx===data.exit.x&&my===data.exit.y){hit=true;addParticles(data.offsetX+mx*cs+cs/2,data.offsetY+my*cs+cs/2,'#48BB78',15);addScorePopup(data.offsetX+mx*cs+cs/2,data.offsetY+my*cs+cs/2,50+data.searchCount*2,'#48BB78');setGameState(p=>({...p,isComplete:true}));}}}}}break;}
      case 'quick-match':{if(d.waiting)break;d.cards.forEach(card=>{if(!card.isMatched&&x>=card.x&&x<=card.x+card.width&&y>=card.y&&y<=card.y+card.height){if(d.flippedCard===null){d.flippedCard=card.id;d.currentShowing=card.id;}else if(d.flippedCard!==card.id){const prev=d.cards.find((c:any)=>c.id===d.flippedCard);if(prev&&prev.emoji===card.emoji){prev.isMatched=true;card.isMatched=true;d.matched++;hit=true;addParticles(card.x+card.width/2,card.y+card.height/2,'#48BB78',10);addScorePopup(card.x+card.width/2,card.y+card.height/2,15,'#48BB78');if(d.matched===d.cards.length/2)setGameState(p=>({...p,isComplete:true}));}d.flippedCard=null;d.waiting=true;d.showTimer=0.8;}}});break;}
    }
    if(hit){setGameState(p=>{const nc=p.combo+1;const nh=p.totalHits+1;return{...p,score:p.score+Math.round(10*(1+p.combo*0.1)),combo:nc,maxCombo:Math.max(p.maxCombo,nc),totalHits:nh,accuracy:Math.round(nh/(nh+p.totalMisses)*100)};});}else if(gameId==='stripe-chase'){setGameState(p=>{const nm=p.totalMisses+1;return{...p,combo:0,totalMisses:nm,accuracy:Math.round(p.totalHits/(p.totalHits+nm)*100)};});}}
  function emitScoreUpdate(){emitGameScore({sessionId,score:gameState.score,accuracy:gameState.accuracy,combo:gameState.combo});}
  function handleGameComplete(){emitGameComplete({sessionId,score:gameState.score,duration:GAME_DURATION-gameState.timeLeft,accuracy:gameState.accuracy,comboMax:gameState.maxCombo,levelCompleted:gameState.level});setStars(gameState.accuracy>=90?3:gameState.accuracy>=70?2:1);setShowResult(true);}
  function handlePause(){setGameState(p=>({...p,isPaused:!p.isPaused}));}
  function handleExit(){emitGameAbort({sessionId});navigate('/games');}
  if(showResult){return(<div className="game-view"><div style={{display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',height:'100vh',background:'linear-gradient(135deg, #4A90E2 0%, #2C5282 100%)',color:'white',padding:'20px'}}><div style={{fontSize:80,marginBottom:20}}>{stars>=3?'🏆':stars>=2?'🥈':'🥉'}</div><h1 style={{fontSize:32,marginBottom:40}}>训练完成！</h1><div style={{marginBottom:32}}>{[1,2,3].map(i=><span key={i} style={{fontSize:40,opacity:i<=stars?1:0.3}}>⭐</span>)}</div><div style={{background:'rgba(255,255,255,0.1)',borderRadius:16,padding:'32px 48px',marginBottom:40,textAlign:'center'}}><div style={{fontSize:48,fontWeight:700,marginBottom:16}}>{gameState.score}</div><div style={{fontSize:18,opacity:0.8}}>总得分</div><div style={{display:'flex',gap:40,marginTop:32,justifyContent:'center'}}><div><div style={{fontSize:24,fontWeight:600}}>{gameState.accuracy}%</div><div style={{fontSize:14,opacity:0.7}}>准确率</div></div><div><div style={{fontSize:24,fontWeight:600}}>{gameState.maxCombo}</div><div style={{fontSize:14,opacity:0.7}}>最大连击</div></div><div><div style={{fontSize:24,fontWeight:600}}>{gameState.level}</div><div style={{fontSize:14,opacity:0.7}}>完成关卡</div></div></div></div><button onClick={()=>navigate('/games')} style={{padding:'16px 48px',fontSize:18,color:'white',background:'#48BB78',border:'none',borderRadius:12,cursor:'pointer'}}>继续训练</button></div></div>);}
  const game=GAMES.find(g=>g.id===gameId);
  return(<div className="game-view"><div className="game-header"><div className="game-title">{game?.name_cn}</div><div className="game-stats"><div className="stat"><div className="stat-value">{Math.floor(gameState.timeLeft/60)}:{String(Math.floor(gameState.timeLeft%60)).padStart(2,'0')}</div><div className="stat-label">时间</div></div><div className="stat"><div className="stat-value">{gameState.score}</div><div className="stat-label">得分</div></div><div className="stat"><div className="stat-value">{gameState.combo}</div><div className="stat-label">连击</div></div><div className="stat"><div className="stat-value">{gameState.accuracy}%</div><div className="stat-label">准确率</div></div></div><button onClick={handlePause} style={{background:'rgba(255,255,255,0.2)',border:'none',color:'white',padding:'12px 16px',borderRadius:8,cursor:'pointer',fontSize:14,fontWeight:500}}>{gameState.isPaused?'▶️ 继续':'⏸️ 暂停'}</button></div><div className="game-canvas-container"><canvas ref={canvasRef} onClick={handleCanvasClick} style={{width:'100%',height:'100%',touchAction:'none'}} /></div><div className="game-footer"><button onClick={handleExit} className="btn btn-secondary" style={{background:'rgba(255,255,255,0.2)',color:'white',border:'none'}}>退出游戏</button></div></div>);
}
`;
fs.appendFileSync(path, append);
console.log('Appended. New size:', fs.statSync(path).size);
